config/routes.rb
Rails.application.routes.draw do
  root "statics#welcome"
  get 'sample', to: 'statics#sample_css'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, except: :index do
    resources :joined_events, only: :index, module: :user
  end
  resources :places
  resources :events do
    resource :favorites, only: %i[create destroy]
    resource :preview, only: :show
    resources :comments, only: %i[create destroy], shallow: true
    resource :join_events, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update] 
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :events, dependent: :destroy
  has_many :join_events, dependent: :destroy
  has_many :joined_events, through: :join_events, source: :event

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :nickname, length: { maximum: 255 }
  validates :body, length: { maximum: 16_383 }

  def joined?(event)
    join_events.exists?(event_id: event.id)
  end
end

app/controllers/user/joined_events_controller.rb
class User::JoinedEventsController < ApplicationController
  def index
    @joined_events = current_user.joined_events.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create]

  # GET /users/1
  def show
    @join_events = current_user&.join_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, success: t('defaults.message.created', item: User.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, success: t('defaults.message.updated', item: User.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :nickname, :body, :avator)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="my-5">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>  
  <div class="my-5">
    <%= f.label :body %>
    <%= f.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>  
  <div class="inline">
    <%= f.submit class: "rounded-lg py-3 px-5 mb-8 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
  <strong class="block font-medium mb-1"><%= User.human_attribute_name(:nickname) %></strong>
  <%= user.nickname %>
  </p>
  <p class="my-5">
  <strong class="block font-medium mb-1"><%= User.human_attribute_name(:body) %></strong>
  <%= user.body %>
  </p>
</div>

app/views/users/_user_favorite.html.erb
<%= render @user %>
<p>ここにお気に入りしたイベント</p>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full h-hull">
  <h1 class="mx-auto md:w-auto mt-8 w-hull font-bold ">ユーザー編集</h1>

  <%= render "form", user: @user %>

</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full h-full">
  <h1 class="mx-auto md:w-auto mt-8 w-hull font-bold ">ユーザー登録</h1>

  <%= render "profiles/form", user: @user %>

  <%= link_to "Login", login_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/show.html.erb
<div class= "mx-auto md:w-2/3 w-full h-full ">
  <h1 class= "mx-auto md:w-auto mt-8 w-hull font-bold ">ユーザー情報</h1>
  <div class= "mx-auto">
    <% if notice.present? %>
      <p class= "py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'ユーザー情報編集', edit_user_path(@user), class: "btn btn-success" %>
    <div class="inline-block ml-2">
      <%= button_to 'ユーザー削除', user_path(@user), method: :delete, class: "btn btn-error" %>
    </div>
    <%= link_to 'イベント作成', new_event_path, class: "btn btn-success" %>
  </div>
<%
=begin
%>
  <% @join_events each do |event| %>
    <%= event.title %>
    <%= event.title %>
  <% end %>
<%
=end
%>
</div>