config/routes.rb
Rails.application.routes.draw do
  root "statics#welcome"
  get 'sample', to: 'statics#sample_css'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, except: :index do
    resources :joined_events, only: :index, module: :user
  end
  resources :places
  resources :events do
    resource :favorites, only: %i[create destroy]
    resource :preview, only: :show
    resources :comments, only: %i[create destroy], shallow: true
    resource :join_events, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update] 
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <%= link_to "EventConnect", root_path, class: "btn btn-ghost normal-case text-xl" %>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal p-0">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "イベント一覧", events_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
        <li><%= link_to "ユーザー登録", new_user_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= object.errors.count %><%= t ('defaults.message.errors_detected')%>:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="flex flex-row-reverse">
    <%= tag.div message, id:"flash-message", class: "alert shadow-lg container my-2 md:mr-10 md:w-1/5" %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer p-10 bg-neutral text-neutral-content">
  <div>
    <span class="footer-title">EventMatch</span> 
    <a class="link link-hover">Branding</a>
    <a class="link link-hover">Design</a>
    <a class="link link-hover">Marketing</a>
    <a class="link link-hover">Advertisement</a>
  </div> 
  <div>
    <span class="footer-title">Company</span> 
    <a class="link link-hover">About us</a>
    <a class="link link-hover">Contact</a>
    <a class="link link-hover">Jobs</a>
    <a class="link link-hover">Press kit</a>
  </div> 
  <div>
    <span class="footer-title">Legal</span> 
    <a class="link link-hover">Terms of use</a>
    <a class="link link-hover">Privacy policy</a>
    <a class="link link-hover">Cookie policy</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <%= link_to "EventConnect", root_path, class: "btn btn-ghost normal-case text-xl" %>
    </div>
    <div class="flex-none">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img src="https://placeimg.com/80/80/people" />
          </div>
        </label>
        <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
          <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "イベント一覧", events_path %></li>
          <li><%= link_to "プロフィール", profile_path %></li>
          <li><%= link_to "参加イベント一覧", user_joined_events_path(current_user) %></li>
          <li><%= button_to t('defaults.logout'), logout_path, method: :delete, data: { turbo: false } %><li>
        </ul>
      </div>
    </div>
  </div>
</header>