config/routes.rb
Rails.application.routes.draw do
  root "statics#welcome"
  get 'sample', to: 'statics#sample_css'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, except: :index do
    resources :joined_events, only: :index, module: :user
  end
  resources :places
  resources :events do
    resource :favorites, only: %i[create destroy]
    resource :preview, only: :show
    resources :comments, only: %i[create destroy], shallow: true
    resource :join_events, only: %i[create destroy]
  end
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update] 
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :place
  has_many :join_events, dependent: :destroy
  has_many :joined_users, through: :join_events, source: :user
  enum state: { open: 0, close: 1 }

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, length: { maximum: 16_383 }
  validates :date, presence: true
  validates :member, numericality: { in: 1..99 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[index]

  # GET /events
  def index
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:user, :place).order(created_at: :desc).page(params[:page])
    # サークルが挟まればこうなるはず
    # @events = @q.result(distinct: true).includes(:cercle).order(created_at: :desc).page(params[:page])
  end

  # GET /events/1
  def show
    @joined_users = @event.joined_users
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to @event, success: t('defaults.message.created', item: Event.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, success: t('defaults.message.updated', item: Event.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, success: t('defaults.message.deleted', item: Event.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :events_image, :date, :member, :place_id)
  end
end

app/views/events/_event.html.erb
<div class="card w-96 bg-base-100 shadow-xl inline-block">
  <figure>
    <img src="https://placeimg.com/400/225/arch" alt=<%= event.title %>/>
  </figure>
    <div id= "event-body" class="card-body">
      <%= link_to event_path(event) do %>
        <div id= "event-header">
          <div class="flex">
            <h2 id= "event-title" class="card-title"><%= event.title %></h2>
            <div id= "event-state" class="badge badge-secondary mt-1 ml-2"><%= event.state %></div>
          </div>
          <p id= "event-title"><%= event.body %></p>
        </div>
        <div id= "event-details" class="card-normal text-right">
          開催日時：<%= l event.date, format: :long %><br>
          場所：<%= event.place.place_name %>
          募集人数：<%= event.member %>
        </div>
      <% end %>
      <div class="card-actions justify-end">
        <% if event.user == current_user %>
          <div class= 'flex'>
            <%=link_to '編集', edit_event_path(event), class: "btn btn-success" %>
            <%=link_to '削除', event_path(event),
              data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' },
              class: "btn btn-error"
            %>
          </div>
        <% else %>
          <div class= "link m-3">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
            </svg>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/events/_event_dedail.html.erb
<div class="card card-compact bg-base-100">
  <div id="<%= dom_id event %>">
    <% if event.events_image? %>
      <!-- <figure><%# image_tag event.events_image.url %></figure> -->
      <figure><%= image_tag '400x300.png'%></figure>
    <% else %>
      <div class="bg-gray-100 overflow-hidden rounded-lg shadow-lg relative mb-6 md:mb-8">
      <img src="https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&q=75&fit=crop&w=600&h=350" loading="lazy" alt="Photo by Minh Pham" class="w-full h-full object-cover object-center" />
    <% end %>
  </div>
    <div class="bg-white py-6 sm:py-8 lg:py-12">
      <div class="max-w-screen-md px-4 md:px-8 mx-auto">
        <%=link_to event_path(event) do %>
          <h1 class="text-gray-800 text-2xl sm:text-3xl font-bold text-center mb-4 md:mb-6">
            <%= event.title %>
          </h1>
        <% end %>
  
    <!-- 開催日時 -->
    <div class="bg-white py-6">
    <div class="max-w-screen-2xl px-4 mx-auto">
      <!-- feature - start -->
      <div class="flex pb-5 md:gap-6">
        <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
          </svg>
        </div>
        <div>
          <p class="text-gray-500">開催日時</p>
          <h3 class="text-lg font-semibold"><%= l event.date, format: :long %></h3>
        </div>
      </div>

      <!-- 活動場所 -->
      <div class="flex pb-5 md:gap-6">
        <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
          </svg>
        </div>
        <div>
        <p class="text-gray-500">活動場所</p>
        <h3 class="text-lg font-semibold"><%= event.place.place_name %></h3>
        <p class="text-gray-500"><%= event.decorate.full_address %></p>
        </div>
      </div>

      <!-- 主催者 -->
      <div class="flex pb-5 md:gap-6">
        <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
          <div class="w-20 md:w-30 h-20 sm:h-14 bg-gray-100 rounded-full overflow-hidden">
          <img src="https://images.unsplash.com/photo-1567515004624-219c11d31f2e??auto=format&q=75&fit=crop&w=256" loading="lazy" alt="Photo by Radu Florin" class="w-full h-full object-cover object-center" />
          </div>
        </div>
        <div>
          <p class="text-gray-500">主催者</p>
          <h3 class="text-lg font-semibold"><%= event.user.nickname %></h3>
        </div>
      </div>

    <!-- 募集人数 -->
    <div class="flex pb-5 md:gap-6">
      <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
        </svg>
      </div>
      <div>
        <p class="text-gray-500">募集人数</p>
        <h3 class="text-lg font-semibold"><%= "#{event.member} 人" %></h3>
        <%= link_to("全員見る", { anchor: "joined_users" }, class: "text-gray-500") %>
      </div>
    </div>
  </div>
</div>
    
        <h2 class="text-gray-800 text-xl sm:text-2xl font-semibold mb-2 md:mb-4">イベント概要</h2>
        <p class="text-gray-500 sm:text-lg mb-6 md:mb-8">
          <%= event.body %>
        </p>
            
        <h2 id="joined_users" class="text-gray-800 text-xl sm:text-2xl font-semibold mb-2 md:mb-4">参加者一覧</h2>
        <% if @joined_users.present? %>
          <%= render partial: 'joined_users', collection: @joined_users %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_event_detail.html.erb
  <div id="<%= dom_id event %>">
    <% if event.events_image? %>
      <!-- <figure><%# image_tag event.events_image.url %></figure> -->
      <figure><%= image_tag '400x300.png'%></figure>
    <% else %>
      <div class="bg-gray-100 overflow-hidden rounded-lg shadow-lg relative mb-6 md:mb-8">
      <img src="https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&q=75&fit=crop&w=600&h=350" loading="lazy" alt="Photo by Minh Pham" class="w-full h-full object-cover object-center" />
    <% end %>
  </div>
    <div class="bg-white py-6 sm:py-8 lg:py-12">
      <div class="max-w-screen-md px-4 md:px-8 mx-auto">
        <%=link_to event_path(event) do %>
          <h1 class="text-gray-800 text-2xl sm:text-3xl font-bold text-center mb-4 md:mb-6">
            <%= event.title %>
          </h1>
        <% end %>
  
    <!-- 開催日時 -->
    <div class="bg-white py-6">
    <div class="max-w-screen-2xl px-4 mx-auto">
      <!-- feature - start -->
      <div class="flex pb-5 md:gap-6">
        <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
          </svg>
        </div>
        <div>
          <p class="text-gray-500">開催日時</p>
          <h3 class="text-lg font-semibold"><%= l event.date, format: :long %></h3>
        </div>
      </div>

      <!-- 活動場所 -->
      <div class="flex pb-5 md:gap-6">
        <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
          </svg>
        </div>
        <div>
        <p class="text-gray-500">活動場所</p>
        <h3 class="text-lg font-semibold"><%= event.place.place_name %></h3>
        <p class="text-gray-500"><%= event.decorate.full_address %></p>
        </div>
      </div>

      <!-- 主催者 -->
      <div class="flex pb-5 md:gap-6">
        <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
          <div class="w-20 md:w-30 h-20 sm:h-14 bg-gray-100 rounded-full overflow-hidden">
          <img src="https://images.unsplash.com/photo-1567515004624-219c11d31f2e??auto=format&q=75&fit=crop&w=256" loading="lazy" alt="Photo by Radu Florin" class="w-full h-full object-cover object-center" />
          </div>
        </div>
        <div>
          <p class="text-gray-500">主催者</p>
          <h3 class="text-lg font-semibold"><%= event.user.nickname %></h3>
        </div>
      </div>

    <!-- 募集人数 -->
    <div class="flex pb-5 md:gap-6">
      <div class="w-12 md:w-14 h-12 md:h-14 flex justify-center items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
        </svg>
      </div>
      <div>
        <p class="text-gray-500">募集人数</p>
        <h3 class="text-lg font-semibold"><%= "#{event.member} 人" %></h3>
        <%= link_to("全員見る", { anchor: "joined_users" }, class: "text-gray-500") %>
      </div>
    </div>
  </div>
</div>
    
        <h2 class="text-gray-800 text-xl sm:text-2xl font-semibold mb-2 md:mb-4">イベント概要</h2>
        <p class="text-gray-500 sm:text-lg mb-6 md:mb-8">
          <%= event.body %>
        </p>
            
        <h2 id="joined_users" class="text-gray-800 text-xl sm:text-2xl font-semibold mb-2 md:mb-4">参加者一覧</h2>
        <% if @joined_users.present? %>
          <%= render partial: 'joined_user', collection: @joined_users %>
        <% end %>
      </div>
    </div>
  </div>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "contents") do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div class="my-5">
    <%= form.label :title, "タイトル(必須)", calss: "text-gray-800" %>
    <%= form.text_field :title, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2" %>
  </div>
    
  <div class="my-5">
    <%= form.label :date, "開催日時(必須)", calss: "text-gray-800" %>
    <%= form.datetime_field :date, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2" %>
  </div>
    
  <div class="my-5">
    <%= form.label :member, "募集人数", calss: "text-gray-800" %>
    <%= form.number_field :member,
      in: 1..99,
      class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2" %>
  </div>

  <div calss="text-gray-800">開催場所</div>

  <div class="my-5 inline-block">
    <%= form.label :district, "地区", calss: "text-gray-400 text-xs" %><br>
    <%= form.collection_select :district, District.all, :id, :name, { include_blank: "地区を選んでください" }, 
        { class: "bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 
                  rounded outline-none transition duration-100 px-3 py-2 mt-2" }  %>
  </div>

  <div class="my-5 inline-block ml-4">
    <%= form.label :place, calss: "text-gray-400 text-xs" %><br id='br'>
    <%= form.select :place, [], { include_blank: "開催場所を選択してください" } , 
        { class: "default-place-select bg-gray-50 text-gray-800 border focus:ring 
                  ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2" } %>
    <% District.all.each do |district| %>
      <template id="<%= "place-of-district#{ district.id }" %>">
        <%= form.collection_select :place, district.places, :id, :place_name, 
        { include_blank: "開催場所を選択してください"}, 
        { class: "bg-gray-50 text-gray-800 border focus:ring ring-indigo-300
                   rounded outline-none transition duration-100 px-3 py-2 mt-2" } %>
      </template>
    <% end %>
  </div>

  <div class="mb-5">
    <%= form.label :address, "住所(東京都〇〇区以降)", calss: "text-gray-400 text-xs" %>
    <%= form.text_field :address, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2" %>
  </div>
  
  <div class="my-5">
    <%= form.label :body, "本文(必須)", calss: "text-gray-800" %>
    <%= form.text_area :body, class: "w-full h-64 bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2" %>
  </div>

  <div class="my-5">
    <%= form.label :events_image, calss: "text-gray-800" %>
    <%= form.file_field :events_image, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2 mt-2 mb-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded-lg outline-none transition duration-100 px-8 py-3 cursor-pointer" %>
  </div>
<% end %>

app/views/events/_joined_user.html.erb
<div class="flex flex-col sm:flex-row items-center gap-2 md:gap-4">
  <div class="w-9 md:w-12 h-9 md:h-12 bg-gray-100 rounded-full overflow-hidden">
    <img src="https://images.unsplash.com/photo-1567515004624-219c11d31f2e??auto=format&q=75&fit=crop&w=256" loading="lazy" alt="Photo by Radu Florin" class="w-full h-full object-cover object-center" />
  </div>
  <div>
    <div class="md:text-lg font-bold text-center sm:text-left"><%= joined_user.nickname %></div>
  </div>
</div>

app/views/events/_joined_users.html.erb
<div class="flex flex-col sm:flex-row items-center gap-2 md:gap-4">
  <div class="w-9 md:w-12 h-9 md:h-12 bg-gray-100 rounded-full overflow-hidden">
    <img src="https://images.unsplash.com/photo-1567515004624-219c11d31f2e??auto=format&q=75&fit=crop&w=256" loading="lazy" alt="Photo by Radu Florin" class="w-full h-full object-cover object-center" />
  </div>
  <div>
    <div class="md:text-lg font-bold text-center sm:text-left"><%= joined_users.nickname %></div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">編集フォーム</h1>

  <%= render "form", event: @event %>

  <%= link_to "Show this event", @event, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to events", events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/events/index.html.erb
<div class="bg-white py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-2xl md:px-8 mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="md:mb-8">
      <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6">イベント一覧</h2>
      <p class="max-w-screen-md text-gray-500 md:text-lg text-center mx-auto">イベントに参加して仲間を見つけよう！</p>
      <div class="flex justify-end">
        <%= link_to 'New event', new_event_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      </div>
      
      <%= search_form_for @q, url: events_path, class:"w-full max-w-md flex gap-2 mb-3 sm:mb-5 m-auto" do |f| %>
        <%= f.search_field :title_or_body_cont, class: "w-full flex-1 bg-gray-white text-gray-800 placeholder-gray-400 border border-gray-300 focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2" %>

        <%= f.submit class:"inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-8 py-2" %>
      <% end %>
    </div>
        
    <div id="events" class="min-w-full">
      <%= render @events %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New event</h1>

  <%= render "form", event: @event %>

  <div class="flex flex-col sm:flex-row sm:justify-center lg:justify-start gap-2.5">
    <%= link_to 'Back to events', events_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium my-10" %>
  </div>
</div>

app/views/events/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
    <div class="card card-compact bg-base-100">
      <%= render partial: 'event_detail', locals: { event: @event } %>
    </div>
    <div class="flex flex-col sm:flex-row sm:justify-center lg:justify-start gap-2.5">
      <% if @event.user_id == current_user.id %>
        <%= link_to '編集', edit_event_path(@event), class: "btn btn-success px-10 mb-5" %>
        <%= button_to '削除', event_path(@event), method: :delete, form: { data: { turbo_confirm: "削除しますか？" } }, class: "btn btn-error px-10 mb-5" %>
      <% else %>
        <% if current_user.joined?(@event) %>
          <%= button_to "参加をキャンセルする", event_join_events_path(@event), method: :delete, form: { data: { turbo_confirm: "イベントの参加をキャンセルしますか？" } }, class: "btn btn-secondary mb-5" %>
        <% else %>
          <%= button_to "参加を申し込む", event_join_events_path(@event), method: :post, form: { data: { turbo_confirm: "イベントに参加しますか？",turbo_post: :post } }, class: "btn btn-primary mb-5" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>